server:
  port: 8085
spring:
  application:
    name: CustomerService
  datasource:
    url: jdbc:postgresql://dpg-d38fkf7fte5s73c1vnfg-a.oregon-postgres.render.com:5432/customers_v825
    username: customers_v825_user
    password: ORMzWyvfOLqr8C7OfvPhj02ZKaEyuXuX
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
